Lao_Qi_Python_Django/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    #path('', views.blog_title, name='blog_title'),
    path('',views.blog_title_c.as_view(),name='blog_title'),
    #path('<int:article_id>/',views.blog_article,name='blog_article')
    path('<int:pk>/',views.blog_article_c.as_view(),name='blog_article'),
    path('information/',views.hello_app)
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.

class BlogArticles(models.Model):
    title = models.CharField(max_length=300)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bolg_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic

# Create your views here.

from .models import BlogArticles


def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, 'blog/titles.html', {'blogs': blogs})


class blog_title_c(generic.ListView):
    template_name = 'blog/titles.html'
    context_object_name = 'blogs'

    def get_queryset(self):
        return BlogArticles.objects.all()


def blog_article(request, blog_id):
    # article = BlogArticles.objects.get(id=article_id)
    article = get_object_or_404(BlogArticles, id=blog_id)
    pub = article.publish
    return render(request, 'blog/content.html', {'article': article, 'pub': pub})


class blog_article_c(generic.DetailView):
    model = BlogArticles
    template_name = 'blog/content.html'
    context_object_name = 'article'


# Webservice test

from spyne import Application, rpc, ServiceBase, Integer, Iterable, Unicode, String
from spyne.protocol.soap import Soap11
from spyne.server.wsgi import WsgiApplication
from spyne.server.django import DjangoApplication
from django.views.decorators.csrf import csrf_exempt
from lxml import etree


class HelloWorldService(ServiceBase):
    @rpc(String, _returns=String,_out_variable_name='output')
    def OperationA(ctx, input):
        try:
            root=etree.fromstring(input)
        except etree.XMLSyntaxError:
            return '<Response><RetInfo><RetCode>-1</RetCode><RetCon>请检查XML格式</RetCon>' \
                   '</RetInfo></Response>'
        else:
            
            "MQ 操作 "


            
            return '<Response><RetInfo><RetCode>0</RetCode><RetCon>成功</RetCon>' \
                   '</RetInfo></Response>'


application = Application([HelloWorldService],
                          tns='http://esb.ewell.cc',
                          name='TestBinding',
                          in_protocol=Soap11(validator='lxml'),
                          out_protocol=Soap11()
                          )

hello_app = csrf_exempt(DjangoApplication(application))

templates/base.html
{% load staticfiles %}
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
   {% include 'header.html' %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
   {% include 'footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/blog/content.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}博客文章{% endblock %}
{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>{{ article.title }}</h1>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <p class="text-center"><span>
                   {{ article.author.username }}
            </span> <span style="margin-left: 20px">{{ article.publish }}</span>

            </p>
            <div>
                {{ article.body }}
            </div>
        </div>
        <div class="col-xs-6 col-md-4">
            <h2>广告</h2>
            <p>一起来学习</p>
            <img src="{% static '/images/1.jpg' %}" width="200px">
        </div>
    </div>
{% endblock %}

templates/blog/titles.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}博客文章{% endblock %}
{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>我的博客</h1>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <ul>
                {% for blog in blogs %}
                    <li><a href="{% url 'blog:blog_article' blog.id %}">{{ blog.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-xs-6 col-md-4">
            <h2>广告</h2>
            <p>一起来学习</p>
            <img src="{% static '/images/1.jpg' %}" width="200px">
        </div>
    </div>
{% endblock %}

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center"> 跟大爷走南闯北</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
             <a class="navbar-brand" href="#" >
                 <img src="{% static 'images/1.jpg' %}" width="60px" class="img-circle">
             </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">博客</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                  <li><a href="#">登陆</a></li>
            </ul>
        </div>
    </nav>

</div>